language: python
python:
- '2.7'
sudo: required
services:
- docker
notifications:
  email:
    recipients:
    - arfathpasha@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    secure: IWQz/e5VViYJJlb33UhQb8Md+eTp1dTMSA9blxeJMRjLpe0o/46A6GYHEY7wgwzxdHEViy1gGlfP1PnGxq4yBcnHDMNqCfAynELHMa9JC273I26hs2koKVZFC86WBnfFoT3u5UJsaCOaG9+j7UQ4j7I6of6PmMF8iFmGxxJgHTUKNhjfx/DJ1v4/UqZy6xAPVunUsd/1XeFPuFPV30+WYcrxkMz3+xBX6iyfSqUYjONW4FJW7FSmpktCv+NzQEK90yH+TWTaOOuJz7/9YL9ykbqaNuZCPUIboU/cuW+45EoxYoEM/ZEVNWsGc9rF8QRFOFaIDEQ2RAu3hPbCnllL4rN7HrChP43BmK14u4CaLQw9wRvesYRvdEGSHIEvN3o4DDO2G4+NU/0eJgpbqAK6rvDrKD3fhfYgLzVsVNsppTdyKcl5AI/33VefiAEYidyQXrbXI4alswut5Yb3DdGRpproLP12O39+5aqGx49LKEEBE5AZVMWvmIxMIDEtueCorYfcRooggD73ms0Xx9xQzPezriwcoIapyieYbvuAMP0JqilrYSffMPXm8Kg35RFzn043SehWhzacbQX9voJeCqsMrMAhGzvH24m4V+ZEtFisGm57cJjrbT1F4qi7yfJEh+a9VxclL8XY9cs/pUFrBM+kWYEUkonfflCJxvwf3LM=

branches:
  only:
  - master
  - travis  #TODO remove

before_install:
- docker version
- python --version
- javac -version
- java -version

install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH
- cd ../
- git clone https://github.com/arfathpasha/kb_cummerbund.git -b travis #TODO change to develop or master
- cd kb_cummerbund
- kb-sdk test || true
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\' test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh

script:
- kb-sdk test

after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/deployment
- sudo cp -R test_local/workdir/kb/deployment/lib /kb/deployment
- ls -l /kb/deployment/lib/kb_cummerbund/
- ls -la
- coverage report -m
- coveralls
